CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int,
  "stripe_id" varchar(255),
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "phone" varchar(10) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "services" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "price" float NOT NULL,
  "description" varchar(10000),
  "expected_time" int NOT NULL,
  "has_image" bool DEFAULT false,
  "stripe_id" varchar(255)
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int NOT NULL,
  "client_id" int NOT NULL,
  "physiotherapeut_id" int NOT NULL,
  "date" timestamp NOT NULL,
  "state" varchar(255) NOT NULL,
  "notes" varchar(10000),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stripe_payment_id" varchar(255),
  "service_id" int NOT NULL,
  "client_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("physiotherapeut_id") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");
